### ISSUE TITLE
`{"error":"redirect_uri_mismatch"}` with omniauth-oauth2 v1.4.0

### ISSUE THREAD

**Issue by konk303** [mixi-inc/omniauth-mixi#3]
https://github.com/intridea/omniauth-oauth2 has changed the spec of `#callback_url` in v1.4.0,
and I'm getting error in omniauth-mixi with it.

```
I, [2016-01-25T18:32:06.796754 #46398]  INFO -- omniauth: (mixi) Callback phase initiated.
E, [2016-01-25T18:32:06.899309 #46398] ERROR -- omniauth: (mixi) Authentication failure! invalid_credentials: OAuth2::Error, redirect_uri_mismatch: 
{"error":"redirect_uri_mismatch"}
```

As https://github.com/intridea/omniauth-oauth2/issues/81#issuecomment-168899933 suggests, downstream gems should re-define `#callback_url` without query strings (as it is used to create redirect_uri of access token get request)

**Comment by kubo39** [comment]
Fixed at #2.
